'use client'

import { useState } from 'react'
import { ArrowRight, Check, ChevronRight, Clipboard, GitFork, Menu, Moon, ShieldCheck, Sun, Terminal, X } from 'lucide-react'
import { Button } from '@/components/ui/button'

const steps = [
  ['01', 'Connect', 'Provide Firebase Admin credentials securely.'],
  ['02', 'Analyze', 'Inspect Firestore and Firebase Auth without writing data.'],
  ['03', 'Generate', 'Turn document patterns into a relational PostgreSQL schema.'],
  ['04', 'Migrate & verify', 'Move data deliberately, then compare source and destination.'],
]

const commands = ['firemigrate init', 'firemigrate inspect', 'firemigrate schema', 'firemigrate migrate --dry-run', 'firemigrate verify']
const githubRepo = process.env.NEXT_PUBLIC_GITHUB_REPO ?? 'EzekielOjochenemi/FireMigrate'
const githubUrl = `https://github.com/${githubRepo}`
const githubStarsUrl = `https://img.shields.io/github/stars/${githubRepo}?style=flat&label=stars&color=c9f27a&labelColor=102326`

function CodeBlock({ children, label = 'terminal' }: { children: React.ReactNode; label?: string }) {
  const [copied, setCopied] = useState(false)
  const text = typeof children === 'string' ? children : ''
  return <div className="overflow-hidden rounded-xl border border-white/10 bg-[#101a1b] shadow-2xl shadow-[#102326]/10">
    <div className="flex items-center justify-between border-b border-white/10 px-4 py-2.5 font-mono text-[10px] uppercase tracking-[0.16em] text-[#91a19b]"><span>{label}</span><button onClick={() => { navigator.clipboard?.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1400) }} className="inline-flex items-center gap-1.5 text-[#c9f27a] hover:text-white" aria-label={`Copy ${label}`}><Clipboard className="size-3.5" />{copied ? 'Copied' : 'Copy'}</button></div>
    <pre className="overflow-x-auto p-5 font-mono text-xs leading-7 text-[#dce8df] sm:text-sm"><code>{children}</code></pre>
  </div>
}

export default function Page() {
  const [dark, setDark] = useState(true)
  const [mobileOpen, setMobileOpen] = useState(false)
  const [installCopied, setInstallCopied] = useState(false)
  const copyInstall = () => { navigator.clipboard?.writeText('npx firemigrate init'); setInstallCopied(true); setTimeout(() => setInstallCopied(false), 1400) }
  return <main className={dark ? 'min-h-screen bg-[#102326] text-[#edf3eb]' : 'min-h-screen bg-[#f7f8f2] text-[#102326]'}>
    <header className={`sticky top-0 z-20 border-b backdrop-blur ${dark ? 'border-white/10 bg-[#102326]/85' : 'border-[#dfe5dc] bg-[#f7f8f2]/85'}`}>
      <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5 sm:px-8"><a href="#top" className="flex items-center gap-2.5"><span className="grid size-8 place-items-center rounded-lg bg-[#c9f27a] font-mono text-[10px] font-bold text-[#102326]">FM</span><span className="font-semibold tracking-tight">FireMigrate</span><span className={`hidden border-l pl-3 font-mono text-[10px] uppercase tracking-[0.14em] sm:inline ${dark ? 'border-white/15 text-[#91a19b]' : 'border-[#d9e0d5] text-[#82908a]'}`}>open source / cli first</span></a><nav className="hidden items-center gap-7 text-sm md:flex"><a href="#how-it-works" className="opacity-70 hover:opacity-100">How it works</a><a href="#safety" className="opacity-70 hover:opacity-100">Safety</a><a href="#roadmap" className="opacity-70 hover:opacity-100">Roadmap</a><a href={githubUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 opacity-70 hover:opacity-100"><GitFork className="size-4" />GitHub</a><button onClick={() => setDark(!dark)} aria-label="Toggle color scheme" className="rounded-md p-2 opacity-70 hover:opacity-100">{dark ? <Sun className="size-4" /> : <Moon className="size-4" />}</button></nav><div className="flex items-center gap-2 md:hidden"><button onClick={() => setDark(!dark)} aria-label="Toggle color scheme" className="rounded-md p-2">{dark ? <Sun className="size-4" /> : <Moon className="size-4" />}</button><button onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle navigation" className="rounded-md p-2">{mobileOpen ? <X className="size-5" /> : <Menu className="size-5" />}</button></div></div>
      {mobileOpen && <nav className={`flex flex-col gap-1 border-t px-5 py-3 text-sm md:hidden ${dark ? 'border-white/10 bg-[#102326]' : 'border-[#dfe5dc] bg-[#f7f8f2]'}`}><a href="#how-it-works" onClick={() => setMobileOpen(false)} className="rounded-md px-2 py-2">How it works</a><a href="#safety" onClick={() => setMobileOpen(false)} className="rounded-md px-2 py-2">Safety</a><a href="#roadmap" onClick={() => setMobileOpen(false)} className="rounded-md px-2 py-2">Roadmap</a><a href={githubUrl} target="_blank" rel="noreferrer" className="rounded-md px-2 py-2">GitHub</a></nav>}
    </header>
    <section id="top" className="mx-auto grid max-w-6xl gap-14 px-5 pb-24 pt-20 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:gap-16 lg:pt-28"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#4c665b] px-3 py-1.5 font-mono text-[10px] uppercase tracking-[0.16em] text-[#c9f27a]"><span className="size-1.5 rounded-full bg-[#c9f27a]" />Firebase → PostgreSQL</div><h1 className="max-w-2xl text-5xl font-semibold leading-[.98] tracking-[-0.06em] sm:text-7xl">Move your Firebase data to <span className="text-[#c9f27a]">PostgreSQL.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-[#aebdb5] sm:text-lg">Analyze your Firebase project, generate a relational PostgreSQL schema, migrate your data, and verify the result.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#get-started" className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-[#c9f27a] px-4 py-2 text-sm font-medium text-[#102326] shadow-xs hover:bg-[#d8fa96]">Get started <ArrowRight className="size-4" /></a><a href={githubUrl} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center justify-center gap-2 rounded-md border border-[#4c665b] bg-transparent px-4 py-2 text-sm font-medium text-[#edf3eb] hover:bg-white/5"><GitFork className="size-4" />View on GitHub</a></div><div className="mt-9 flex flex-wrap items-center gap-5 font-mono text-[10px] uppercase tracking-[0.12em] text-[#789087]"><span>MIT licensed</span><span>·</span><span>TypeScript</span><span>·</span><span>CLI first</span><a href={githubUrl} target="_blank" rel="noreferrer" aria-label={`Open ${githubRepo} on GitHub`}><img src={githubStarsUrl} alt="GitHub star count" className="h-5 w-auto" /></a></div></div><CodeBlock label="firemigrate inspect">{`$ npx firemigrate inspect\n\n✓ Firebase credentials validated\n✓ Firestore discovered\n✓ 14 collections found\n✓ 182,491 documents analyzed\n✓ Firebase Auth discovered\n\nWarnings:\n⚠ 3 collections contain inconsistent field types\n⚠ 2 relationships require manual review\n\nReady to generate PostgreSQL schema.`}</CodeBlock></section>
    <section className={dark ? 'border-y border-white/10 bg-[#0d1d1f]' : 'border-y border-[#dfe5dc] bg-white/60'}><div className="mx-auto grid max-w-6xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#8ca49a]">The problem</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Firebase makes starting easy. Leaving it shouldn&apos;t mean rebuilding everything by hand.</h2></div><div className="grid grid-cols-[1fr_auto_1fr_auto_1fr] items-center gap-2 font-mono text-center text-xs sm:gap-4"><div className="rounded-lg border border-[#405b51] p-4">Firebase</div><ChevronRight className="size-4 text-[#c9f27a]" /><div className="rounded-lg border border-[#405b51] p-4">Analyze</div><ChevronRight className="size-4 text-[#c9f27a]" /><div className="rounded-lg border border-[#c9f27a]/50 bg-[#c9f27a]/10 p-4 text-[#c9f27a]">PostgreSQL</div></div></div></section>
    <section id="how-it-works" className="mx-auto max-w-6xl px-5 py-24 sm:px-8"><div className="max-w-xl"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#829b90]">A deliberate path</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Inspect first. Write last.</h2></div><div className="mt-12 grid gap-px overflow-hidden rounded-xl border border-[#385249] bg-[#385249] md:grid-cols-4">{steps.map(([number, title, text]) => <div key={number} className={dark ? 'bg-[#102326] p-6' : 'bg-[#f7f8f2] p-6'}><div className="font-mono text-xs text-[#c9f27a]">{number}</div><h3 className="mt-12 text-lg font-medium">{title}</h3><p className="mt-2 text-sm leading-6 opacity-65">{text}</p></div>)}</div></section>
    <section className={dark ? 'border-y border-white/10 bg-[#0d1d1f]' : 'border-y border-[#dfe5dc] bg-white/60'}><div className="mx-auto grid max-w-6xl gap-12 px-5 py-24 sm:px-8 lg:grid-cols-2 lg:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#829b90]">Firestore → PostgreSQL</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]">Relational by default. Honest about uncertainty.</h2><p className="mt-5 max-w-lg text-sm leading-7 opacity-70">FireMigrate analyzes collections, nested collections, field types, timestamps, maps, arrays, and references. It attempts to preserve obvious relationships instead of dumping every document into a JSON column.</p></div><CodeBlock label="schema proposal">{`Firestore                         PostgreSQL\n\nusers/{uid}                       users\n  name                              id\n  email                             firebase_uid\n                                  name\nusers/{uid}/projects/{id}         email\n  title\n  description                      projects\n                                  id\n                                  user_id → users.id\n                                  title\n                                  description`}</CodeBlock></div></section>
    <section id="safety" className="mx-auto max-w-6xl px-5 py-24 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#829b90]">Migration safety</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Confidence before convenience.</h2><p className="mt-5 max-w-md text-sm leading-7 opacity-70">Credentials stay server-side. Writes stay explicit. Warnings stay visible. The default workflow is designed for review before production.</p></div><div className="grid gap-3 sm:grid-cols-2">{['Dry runs and schema preview','Non-destructive defaults','Detailed migration warnings','Read-only verification','Provider-aware Auth analysis','No credential exposure'].map(item => <div key={item} className="flex items-center gap-3 rounded-lg border border-[#385249] p-4 text-sm"><ShieldCheck className="size-4 shrink-0 text-[#c9f27a]" />{item}</div>)}</div></div></section>
    <section id="get-started" className={dark ? 'border-y border-white/10 bg-[#c9f27a] text-[#102326]' : 'border-y border-[#b8d888] bg-[#dff4b0] text-[#102326]'}><div className="mx-auto grid max-w-6xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] opacity-65">Get started</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Your migration starts with a read-only inspection.</h2><p className="mt-4 max-w-xl text-sm leading-6 opacity-75">Configure Firebase Admin credentials and a PostgreSQL connection. Never commit service-account keys or print them in logs.</p></div><button onClick={copyInstall} className="flex items-center gap-4 rounded-xl bg-[#102326] px-5 py-4 text-left font-mono text-sm text-[#dce8df] shadow-xl"><Terminal className="size-4 text-[#c9f27a]" /><span>npx firemigrate init</span><Clipboard className="ml-4 size-4 text-[#91a19b]" />{installCopied && <span className="text-xs text-[#c9f27a]">Copied</span>}</button></div></section>
    <section id="roadmap" className="mx-auto max-w-6xl px-5 py-24 sm:px-8"><div className="grid gap-12 md:grid-cols-2"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#829b90]">CLI surface</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]">One clear command at a time.</h2><div className="mt-7 flex flex-col gap-2">{commands.map((command, index) => <div key={command} className="flex items-center gap-3 rounded-lg border border-[#385249] px-4 py-3 font-mono text-sm"><span className="text-[#c9f27a]">0{index + 1}</span><span>{command}</span><Check className="ml-auto size-4 text-[#789087]" /></div>)}</div></div><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#829b90]">Built in the open</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]">A foundation developers can inspect and improve.</h2><p className="mt-5 text-sm leading-7 opacity-70">FireMigrate is MIT-licensed and built for contributors: improve analyzers, add safer mappings, report edge cases, and help make Firebase migrations less mysterious.</p><a href={githubUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 text-sm font-medium text-[#c9f27a] hover:underline">Read the contribution guide <ArrowRight className="size-4" /></a></div></div></section>
    <footer className="border-t border-white/10"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-5 py-8 text-xs opacity-55 sm:flex-row sm:items-center sm:justify-between sm:px-8"><span className="font-mono">FireMigrate · MIT licensed</span><span>Firebase → PostgreSQL, with the sharp edges visible.</span></div></footer>
  </main>
}
